return {
  weapons = {
    WEAPON_PISTOL = {
      { label = 'Extended Clip', component = 'COMPONENT_PISTOL_CLIP_02', slot = 'mag' },
      { label = 'Flashlight', component = 'COMPONENT_AT_PI_FLSH' },
      { label = 'Suppressor', component = 'COMPONENT_AT_PI_SUPP_02', slot = 'muzzle' },
      { label = 'Luxury Finish', component = 'COMPONENT_PISTOL_VARMOD_LUXE', slot = 'skin' },
    },
    WEAPON_COMBATPISTOL = {
      { label = 'Extended Clip', component = 'COMPONENT_COMBATPISTOL_CLIP_02', slot = 'mag' },
      { label = 'Flashlight', component = 'COMPONENT_AT_PI_FLSH' },
      { label = 'Suppressor', component = 'COMPONENT_AT_PI_SUPP', slot = 'muzzle' },
      { label = 'Gilded Finish', component = 'COMPONENT_COMBATPISTOL_VARMOD_LOWRIDER', slot = 'skin' },
    },
    WEAPON_PISTOL_MK2 = {
      { label = 'Extended Mag', component = 'COMPONENT_PISTOL_MK2_CLIP_02', slot = 'mag' },
      { label = 'Tracer Rounds', component = 'COMPONENT_PISTOL_MK2_CLIP_TRACER', slot = 'mag' },
      { label = 'Hollow Point Rounds', component = 'COMPONENT_PISTOL_MK2_CLIP_HOLLOWPOINT', slot = 'mag' },
      { label = 'FMJ Rounds', component = 'COMPONENT_PISTOL_MK2_CLIP_FMJ', slot = 'mag' },
      { label = 'Flashlight', component = 'COMPONENT_AT_PI_FLSH_02' },
      { label = 'Mounted Scope', component = 'COMPONENT_AT_PI_RAIL', slot = 'optic' },
      { label = 'Suppressor', component = 'COMPONENT_AT_PI_SUPP_02', slot = 'muzzle' },
      { label = 'Compensator', component = 'COMPONENT_AT_PI_COMP', slot = 'muzzle' },
    },
    WEAPON_APPISTOL = {
      { label = 'Extended Clip', component = 'COMPONENT_APPISTOL_CLIP_02', slot = 'mag' },
      { label = 'Flashlight', component = 'COMPONENT_AT_PI_FLSH' },
      { label = 'Suppressor', component = 'COMPONENT_AT_PI_SUPP', slot = 'muzzle' },
      { label = 'Gilded Finish', component = 'COMPONENT_APPISTOL_VARMOD_LUXE', slot = 'skin' },
    },
    WEAPON_PUMPSHOTGUN = {
      { label = 'Flashlight', component = 'COMPONENT_AT_AR_FLSH' },
      { label = 'Suppressor', component = 'COMPONENT_AT_SR_SUPP', slot = 'muzzle' },
    },
    WEAPON_PUMPSHOTGUN_MK2 = {
      { label = 'Incendiary Shells', component = 'COMPONENT_PUMPSHOTGUN_MK2_CLIP_INCENDIARY', slot = 'mag' },
      { label = 'Hollow Point Shells', component = 'COMPONENT_PUMPSHOTGUN_MK2_CLIP_HOLLOWPOINT', slot = 'mag' },
      { label = 'Armor Piercing Shells', component = 'COMPONENT_PUMPSHOTGUN_MK2_CLIP_ARMORPIERCING', slot = 'mag' },
      { label = 'Flashlight', component = 'COMPONENT_AT_AR_FLSH' },
      { label = 'Holographic Sight', component = 'COMPONENT_AT_SIGHTS', slot = 'optic' },
      { label = 'Small Scope', component = 'COMPONENT_AT_SCOPE_MACRO_MK2', slot = 'optic' },
      { label = 'Medium Scope', component = 'COMPONENT_AT_SCOPE_SMALL_MK2', slot = 'optic' },
      { label = 'Suppressor', component = 'COMPONENT_AT_SR_SUPP_03', slot = 'muzzle' },
      { label = 'Muzzle Brake', component = 'COMPONENT_AT_MUZZLE_08', slot = 'muzzle' },
    },
    WEAPON_SMG = {
      { label = 'Extended Clip', component = 'COMPONENT_SMG_CLIP_02', slot = 'mag' },
      { label = 'Drum Magazine', component = 'COMPONENT_SMG_CLIP_03', slot = 'mag' },
      { label = 'Flashlight', component = 'COMPONENT_AT_AR_FLSH' },
      { label = 'Holographic Scope', component = 'COMPONENT_AT_SCOPE_MACRO_02', slot = 'optic' },
      { label = 'Suppressor', component = 'COMPONENT_AT_PI_SUPP', slot = 'muzzle' },
      { label = 'Luxury Finish', component = 'COMPONENT_SMG_VARMOD_LUXE', slot = 'skin' },
    },
    WEAPON_MICROSMG = {
      { label = 'Extended Clip', component = 'COMPONENT_MICROSMG_CLIP_02', slot = 'mag' },
      { label = 'Flashlight', component = 'COMPONENT_AT_PI_FLSH' },
      { label = 'Scope', component = 'COMPONENT_AT_SCOPE_MACRO', slot = 'optic' },
      { label = 'Suppressor', component = 'COMPONENT_AT_AR_SUPP_02', slot = 'muzzle' },
      { label = 'Luxury Finish', component = 'COMPONENT_MICROSMG_VARMOD_LUXE', slot = 'skin' },
    },
    WEAPON_MINISMG = {
      { label = 'Extended Clip', component = 'COMPONENT_MINISMG_CLIP_02', slot = 'mag' },
    },
    WEAPON_SMG_MK2 = {
      { label = 'Extended Mag', component = 'COMPONENT_SMG_MK2_CLIP_02', slot = 'mag' },
      { label = 'Tracer Rounds', component = 'COMPONENT_SMG_MK2_CLIP_TRACER', slot = 'mag' },
      { label = 'Hollow Point Rounds', component = 'COMPONENT_SMG_MK2_CLIP_HOLLOWPOINT', slot = 'mag' },
      { label = 'FMJ Rounds', component = 'COMPONENT_SMG_MK2_CLIP_FMJ', slot = 'mag' },
      { label = 'Flashlight', component = 'COMPONENT_AT_AR_FLSH' },
      { label = 'Holographic Sight', component = 'COMPONENT_AT_SIGHTS_SMG', slot = 'optic' },
      { label = 'Small Scope', component = 'COMPONENT_AT_SCOPE_MACRO_02_SMG_MK2', slot = 'optic' },
      { label = 'Medium Scope', component = 'COMPONENT_AT_SCOPE_SMALL_SMG_MK2', slot = 'optic' },
      { label = 'Suppressor', component = 'COMPONENT_AT_PI_SUPP', slot = 'muzzle' },
      { label = 'Muzzle Brake', component = 'COMPONENT_AT_MUZZLE_01', slot = 'muzzle' },
    },
    WEAPON_ASSAULTRIFLE = {
      { label = 'Extended Clip', component = 'COMPONENT_ASSAULTRIFLE_CLIP_02', slot = 'mag' },
      { label = 'Drum Magazine', component = 'COMPONENT_ASSAULTRIFLE_CLIP_03', slot = 'mag' },
      { label = 'Flashlight', component = 'COMPONENT_AT_AR_FLSH' },
      { label = 'Macro Scope', component = 'COMPONENT_AT_SCOPE_MACRO', slot = 'optic' },
      { label = 'Suppressor', component = 'COMPONENT_AT_AR_SUPP_02', slot = 'muzzle' },
      { label = 'Grip', component = 'COMPONENT_AT_AR_AFGRIP' },
      { label = 'Luxury Finish', component = 'COMPONENT_ASSAULTRIFLE_VARMOD_LUXE', slot = 'skin' },
    },
    WEAPON_CARBINERIFLE = {
      { label = 'Extended Clip', component = 'COMPONENT_CARBINERIFLE_CLIP_02', slot = 'mag' },
      { label = 'Box Magazine', component = 'COMPONENT_CARBINERIFLE_CLIP_03', slot = 'mag' },
      { label = 'Flashlight', component = 'COMPONENT_AT_AR_FLSH' },
      { label = 'Medium Scope', component = 'COMPONENT_AT_SCOPE_MEDIUM', slot = 'optic' },
      { label = 'Suppressor', component = 'COMPONENT_AT_AR_SUPP', slot = 'muzzle' },
      { label = 'Grip', component = 'COMPONENT_AT_AR_AFGRIP' },
      { label = 'Luxury Finish', component = 'COMPONENT_CARBINERIFLE_VARMOD_LUXE', slot = 'skin' },
    },
    WEAPON_CARBINERIFLE_MK2 = {
      { label = 'Extended Mag', component = 'COMPONENT_CARBINERIFLE_MK2_CLIP_02', slot = 'mag' },
      { label = 'Tracer Rounds', component = 'COMPONENT_CARBINERIFLE_MK2_CLIP_TRACER', slot = 'mag' },
      { label = 'Armor Piercing Rounds', component = 'COMPONENT_CARBINERIFLE_MK2_CLIP_ARMORPIERCING', slot = 'mag' },
      { label = 'FMJ Rounds', component = 'COMPONENT_CARBINERIFLE_MK2_CLIP_FMJ', slot = 'mag' },
      { label = 'Flashlight', component = 'COMPONENT_AT_AR_FLSH' },
      { label = 'Holographic Sight', component = 'COMPONENT_AT_SIGHTS', slot = 'optic' },
      { label = 'Small Scope', component = 'COMPONENT_AT_SCOPE_MACRO_MK2', slot = 'optic' },
      { label = 'Large Scope', component = 'COMPONENT_AT_SCOPE_MEDIUM_MK2', slot = 'optic' },
      { label = 'Suppressor', component = 'COMPONENT_AT_AR_SUPP', slot = 'muzzle' },
      { label = 'Muzzle Brake', component = 'COMPONENT_AT_MUZZLE_01', slot = 'muzzle' },
      { label = 'Heavy Barrel', component = 'COMPONENT_AT_CR_BARREL_02', slot = 'barrel' },
    },
    WEAPON_ADVANCEDRIFLE = {
      { label = 'Extended Clip', component = 'COMPONENT_ADVANCEDRIFLE_CLIP_02', slot = 'mag' },
      { label = 'Flashlight', component = 'COMPONENT_AT_AR_FLSH' },
      { label = 'Small Scope', component = 'COMPONENT_AT_SCOPE_SMALL', slot = 'optic' },
      { label = 'Suppressor', component = 'COMPONENT_AT_AR_SUPP', slot = 'muzzle' },
      { label = 'Luxury Finish', component = 'COMPONENT_ADVANCEDRIFLE_VARMOD_LUXE', slot = 'skin' },
    },
    WEAPON_SNIPERRIFLE = {
      { label = 'Large Scope', component = 'COMPONENT_AT_SCOPE_LARGE', slot = 'optic' },
      { label = 'Advanced Scope', component = 'COMPONENT_AT_SCOPE_MAX', slot = 'optic' },
      { label = 'Suppressor', component = 'COMPONENT_AT_AR_SUPP_02', slot = 'muzzle' },
    },
    WEAPON_HEAVYSNIPER = {
      { label = 'Large Scope', component = 'COMPONENT_AT_SCOPE_LARGE', slot = 'optic' },
      { label = 'Advanced Scope', component = 'COMPONENT_AT_SCOPE_MAX', slot = 'optic' },
    },
    WEAPON_HEAVYSNIPER_MK2 = {
      { label = 'Extended Mag', component = 'COMPONENT_HEAVYSNIPER_MK2_CLIP_02', slot = 'mag' },
      { label = 'Armor Piercing Rounds', component = 'COMPONENT_HEAVYSNIPER_MK2_CLIP_ARMORPIERCING', slot = 'mag' },
      { label = 'Explosive Rounds', component = 'COMPONENT_HEAVYSNIPER_MK2_CLIP_EXPLOSIVE', slot = 'mag' },
      { label = 'FMJ Rounds', component = 'COMPONENT_HEAVYSNIPER_MK2_CLIP_FMJ', slot = 'mag' },
      { label = 'Thermal Scope', component = 'COMPONENT_AT_SCOPE_THERMAL', slot = 'optic' },
      { label = 'Night Vision Scope', component = 'COMPONENT_AT_SCOPE_NV', slot = 'optic' },
      { label = 'Advanced Scope', component = 'COMPONENT_AT_SCOPE_LARGE_MK2', slot = 'optic' },
      { label = 'Suppressor', component = 'COMPONENT_AT_SR_SUPP_03', slot = 'muzzle' },
      { label = 'Muzzle Brake', component = 'COMPONENT_AT_MUZZLE_09', slot = 'muzzle' },
      { label = 'Heavy Barrel', component = 'COMPONENT_AT_SR_BARREL_02', slot = 'barrel' },
    },
    WEAPON_COMBATMG = {
      { label = 'Extended Clip', component = 'COMPONENT_COMBATMG_CLIP_02', slot = 'mag' },
      { label = 'Medium Scope', component = 'COMPONENT_AT_SCOPE_MEDIUM', slot = 'optic' },
      { label = 'Grip', component = 'COMPONENT_AT_AR_AFGRIP' },
    },
  }
}
